from protein_complex_converter.parser import parse_complex_tab, convert_to_mitab, Row, MitabRow, serialize_to_mitab


def test_parse_complex_tab():
    ct = """#Complex ac	Recommended name	Aliases for complex	Taxonomy identifier	Identifiers (and stoichiometry) of molecules in complex	Evidence Code	Experimental evidence	Go Annotations	Cross references	Description	Complex properties	Complex assembly	Ligand	Disease	Agonist	Antagonist	Comment	Source	Expanded participant list
CPX-1	SMAD2-SMAD3-SMAD4 complex	SMAD2/SMAD3/SMAD4 transcription factor complex	9606	P84022(1)|Q13485(1)|Q15796(1)	ECO:0005547(biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion)	-	GO:0006351(transcription, DNA-templated)|GO:0007179(transforming growth factor beta receptor signaling pathway)|GO:0003700(sequence-specific DNA binding transcription factor activity)|GO:0003690(double-stranded DNA binding)|GO:0032924(activin receptor signaling pathway)|GO:0071144(heteromeric SMAD protein complex)	pubmed:16322555(see-also)|complex portal:CPX-1(complex-primary)|wwpdb:1U7V(subset)	A transcription factor complex which binds to the promoters of target genes and recruits co-activators and histone acetyltransferases, such as p300, CBP and P300/CBP-associated factor, facilitating transcription. In response to TGF-beta/activin-family protein binding, TGF-beta type II receptors phosphorylate TGF-beta type I receptors (ALK4, 5 and 7) which in turn phosphorylates SMAD2 on two Ser-465 and Ser-467, and SMAD3 on Ser-423 and Ser-425. This enables binding to SMAD4 to form heteromeric SMAD complexes that enter the nucleus to initiate gene transcription. Because of their relatively low DNA-binding affinity, SMAD complexes interact with a wide variety of DNA-binding proteins. Crosstalk with other signalling pathways and interaction with other DNA-binding cofactors define the specific binding patterns of SMADs; in addition, interaction with coactivators/corepressors modulates their transcriptional activity.	Preferential formation of the regulatory R-Smad/SMAD4 heterotrimer over the R-Smad homotrimer is largely enthalpy driven, contributed by the unique presence of strong electrostatic interactions within the heterotrimeric interfaces. These electrostatic interactions exist only in the heterotrimer due to specific charged residues in the SMAD4 subunit, Asp-493 and Arg-378, mediating complementary electrostatic interactions with the neighbouring R-Smad subunits.	Heterotrimer	-	-	-	-	-	psi-mi:"MI:0469"(IntAct)	P84022(1)|Q13485(1)|Q15796(1)"""
    assert parse_complex_tab(ct) == [Row(complex="CPX-1", uniprot_ids=["P84022", "Q13485", "Q15796"], pubmed_ids=["pubmed:16322555"], first_author_name=['Massagué et al. (2005)'])]

def test_convert_to_mitab():
    ct = """#Complex ac	Recommended name	Aliases for complex	Taxonomy identifier	Identifiers (and stoichiometry) of molecules in complex	Evidence Code	Experimental evidence	Go Annotations	Cross references	Description	Complex properties	Complex assembly	Ligand	Disease	Agonist	Antagonist	Comment	Source	Expanded participant list
CPX-1	SMAD2-SMAD3-SMAD4 complex	SMAD2/SMAD3/SMAD4 transcription factor complex	9606	P84022(1)|Q13485(1)|Q15796(1)	ECO:0005547(biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion)	-	GO:0006351(transcription, DNA-templated)|GO:0007179(transforming growth factor beta receptor signaling pathway)|GO:0003700(sequence-specific DNA binding transcription factor activity)|GO:0003690(double-stranded DNA binding)|GO:0032924(activin receptor signaling pathway)|GO:0071144(heteromeric SMAD protein complex)	pubmed:16322555(see-also)|complex portal:CPX-1(complex-primary)|wwpdb:1U7V(subset)	A transcription factor complex which binds to the promoters of target genes and recruits co-activators and histone acetyltransferases, such as p300, CBP and P300/CBP-associated factor, facilitating transcription. In response to TGF-beta/activin-family protein binding, TGF-beta type II receptors phosphorylate TGF-beta type I receptors (ALK4, 5 and 7) which in turn phosphorylates SMAD2 on two Ser-465 and Ser-467, and SMAD3 on Ser-423 and Ser-425. This enables binding to SMAD4 to form heteromeric SMAD complexes that enter the nucleus to initiate gene transcription. Because of their relatively low DNA-binding affinity, SMAD complexes interact with a wide variety of DNA-binding proteins. Crosstalk with other signalling pathways and interaction with other DNA-binding cofactors define the specific binding patterns of SMADs; in addition, interaction with coactivators/corepressors modulates their transcriptional activity.	Preferential formation of the regulatory R-Smad/SMAD4 heterotrimer over the R-Smad homotrimer is largely enthalpy driven, contributed by the unique presence of strong electrostatic interactions within the heterotrimeric interfaces. These electrostatic interactions exist only in the heterotrimer due to specific charged residues in the SMAD4 subunit, Asp-493 and Arg-378, mediating complementary electrostatic interactions with the neighbouring R-Smad subunits.	Heterotrimer	-	-	-	-	-	psi-mi:"MI:0469"(IntAct)	P84022(1)|Q13485(1)|Q15796(1)"""
    assert list(convert_to_mitab(parse_complex_tab(ct))) == [MitabRow(uida="CPX-1",uidb="P84022",author="Massagué et al. (2005)",pmids="pubmed:16322555"),MitabRow(uida="CPX-1",uidb="Q13485",author="Massagué et al. (2005)",pmids="pubmed:16322555"),MitabRow(uida="CPX-1",uidb="Q15796",author="Massagué et al. (2005)",pmids="pubmed:16322555")]

def test_serialize_to_mitab():
    ct = """#Complex ac	Recommended name	Aliases for complex	Taxonomy identifier	Identifiers (and stoichiometry) of molecules in complex	Evidence Code	Experimental evidence	Go Annotations	Cross references	Description	Complex properties	Complex assembly	Ligand	Disease	Agonist	Antagonist	Comment	Source	Expanded participant list
CPX-1	SMAD2-SMAD3-SMAD4 complex	SMAD2/SMAD3/SMAD4 transcription factor complex	9606	P84022(1)|Q13485(1)|Q15796(1)	ECO:0005547(biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion)	-	GO:0006351(transcription, DNA-templated)|GO:0007179(transforming growth factor beta receptor signaling pathway)|GO:0003700(sequence-specific DNA binding transcription factor activity)|GO:0003690(double-stranded DNA binding)|GO:0032924(activin receptor signaling pathway)|GO:0071144(heteromeric SMAD protein complex)	pubmed:16322555(see-also)|complex portal:CPX-1(complex-primary)|wwpdb:1U7V(subset)	A transcription factor complex which binds to the promoters of target genes and recruits co-activators and histone acetyltransferases, such as p300, CBP and P300/CBP-associated factor, facilitating transcription. In response to TGF-beta/activin-family protein binding, TGF-beta type II receptors phosphorylate TGF-beta type I receptors (ALK4, 5 and 7) which in turn phosphorylates SMAD2 on two Ser-465 and Ser-467, and SMAD3 on Ser-423 and Ser-425. This enables binding to SMAD4 to form heteromeric SMAD complexes that enter the nucleus to initiate gene transcription. Because of their relatively low DNA-binding affinity, SMAD complexes interact with a wide variety of DNA-binding proteins. Crosstalk with other signalling pathways and interaction with other DNA-binding cofactors define the specific binding patterns of SMADs; in addition, interaction with coactivators/corepressors modulates their transcriptional activity.	Preferential formation of the regulatory R-Smad/SMAD4 heterotrimer over the R-Smad homotrimer is largely enthalpy driven, contributed by the unique presence of strong electrostatic interactions within the heterotrimeric interfaces. These electrostatic interactions exist only in the heterotrimer due to specific charged residues in the SMAD4 subunit, Asp-493 and Arg-378, mediating complementary electrostatic interactions with the neighbouring R-Smad subunits.	Heterotrimer	-	-	-	-	-	psi-mi:"MI:0469"(IntAct)	P84022(1)|Q13485(1)|Q15796(1)"""
    expected = """#uidA	uidB	author	pmids\r
CPX-1	P84022	Massagué et al. (2005)	pubmed:16322555\r
CPX-1	Q13485	Massagué et al. (2005)	pubmed:16322555\r
CPX-1	Q15796	Massagué et al. (2005)	pubmed:16322555\r
"""
    assert serialize_to_mitab(convert_to_mitab(parse_complex_tab(ct))) == expected